"""
DAG generation and deployment service.
"""
import os
import re
from typing import Optional, List
from datetime import datetime

from app.core.config import settings


class DAGGenerator:
    """Service for generating and deploying Airflow DAGs."""

    DAG_TEMPLATE = '''"""
{description}
Auto-generated by Big Data Platform
Generated at: {generated_at}
"""
from datetime import datetime, timedelta
from airflow import DAG
from airflow.providers.common.sql.operators.sql import SQLExecuteQueryOperator
from airflow.operators.python import PythonOperator
from airflow.operators.empty import EmptyOperator
{extra_imports}

default_args = {{
    "owner": "bigdata_platform",
    "depends_on_past": False,
    "start_date": datetime({start_year}, {start_month}, {start_day}),
    "retries": {retries},
    "retry_delay": timedelta(minutes={retry_delay}),
    {email_config}
}}

with DAG(
    dag_id="{dag_id}",
    default_args=default_args,
    description="{description}",
    schedule_interval="{schedule_interval}",
    catchup=False,
    tags={tags},
) as dag:

{task_definitions}

{task_dependencies}
'''

    def __init__(self, dags_folder: str = "/opt/airflow/dags/generated"):
        self.dags_folder = dags_folder
        os.makedirs(self.dags_folder, exist_ok=True)

    def sanitize_dag_id(self, name: str) -> str:
        """Convert name to valid DAG ID."""
        # Replace spaces and hyphens with underscores
        dag_id = re.sub(r"[\s\-]+", "_", name.lower())
        # Remove invalid characters
        dag_id = re.sub(r"[^a-z0-9_]", "", dag_id)
        # Ensure it starts with a letter
        if dag_id and not dag_id[0].isalpha():
            dag_id = "dag_" + dag_id
        return dag_id or "unnamed_dag"

    def generate_sql_dag(
        self,
        name: str,
        description: str,
        sql_content: str,
        conn_id: str,
        schedule_interval: str,
        alert_email: Optional[str] = None,
        dependencies: Optional[List[str]] = None,
        retries: int = 1,
        retry_delay: int = 5,
    ) -> str:
        """Generate DAG code for SQL execution."""
        dag_id = self.sanitize_dag_id(name)
        now = datetime.utcnow()

        # Build email config
        email_config = ""
        if alert_email:
            email_config = f'"email": ["{alert_email}"],\n    "email_on_failure": True,'

        # Build extra imports for dependencies
        extra_imports = ""
        if dependencies:
            extra_imports = "from airflow.sensors.external_task import ExternalTaskSensor"

        # Build task definitions
        tasks = []

        # Add dependency sensors
        if dependencies:
            for i, dep_dag in enumerate(dependencies):
                tasks.append(f'''    wait_for_{dep_dag} = ExternalTaskSensor(
        task_id="wait_for_{dep_dag}",
        external_dag_id="{dep_dag}",
        mode="reschedule",
        timeout=3600,
    )
''')

        # Add SQL execution task
        # Escape the SQL content for Python string
        escaped_sql = sql_content.replace('"""', '\\"\\"\\"').replace("'''", "\\'\\'\\'")
        tasks.append(f'''    execute_sql = SQLExecuteQueryOperator(
        task_id="execute_sql",
        conn_id="{conn_id}",
        sql="""
{escaped_sql}
        """,
    )
''')

        # Build task dependencies
        task_deps = []
        if dependencies:
            dep_tasks = " >> ".join([f"wait_for_{d}" for d in dependencies])
            task_deps.append(f"    {dep_tasks} >> execute_sql")

        dag_code = self.DAG_TEMPLATE.format(
            description=description,
            generated_at=now.isoformat(),
            dag_id=dag_id,
            schedule_interval=schedule_interval,
            start_year=now.year,
            start_month=now.month,
            start_day=now.day,
            retries=retries,
            retry_delay=retry_delay,
            email_config=email_config,
            extra_imports=extra_imports,
            tags=["bigdata_platform", "sql_execution"],
            task_definitions="\n".join(tasks),
            task_dependencies="\n".join(task_deps) if task_deps else "    pass",
        )

        return dag_code

    def deploy_dag(self, dag_id: str, dag_code: str) -> str:
        """Deploy DAG code to Airflow dags folder."""
        file_path = os.path.join(self.dags_folder, f"{dag_id}.py")
        with open(file_path, "w") as f:
            f.write(dag_code)
        return file_path

    def remove_dag(self, dag_id: str) -> bool:
        """Remove a deployed DAG file."""
        file_path = os.path.join(self.dags_folder, f"{dag_id}.py")
        if os.path.exists(file_path):
            os.remove(file_path)
            return True
        return False

    def list_deployed_dags(self) -> List[str]:
        """List all deployed DAG files."""
        dags = []
        for filename in os.listdir(self.dags_folder):
            if filename.endswith(".py"):
                dags.append(filename[:-3])  # Remove .py extension
        return dags
